import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom-header/header";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
const manRopeSans = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  

  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            manRopeSans.variable,
          )}
        >
          <Toaster />
          <Header />
          <main>{children}</main>
        </body>
      </StoreProvider>
    </html>
  );
}
